# 服务配置
server:
  port: 80
  https:
    enable: true

# 启用Swagger文档
swagger.enable: true
# 启用全局方法日志
appMethodLogger.enable: true

# Spring配置
spring:
  profiles:
    active: default
  http:
    multipart: #文件上传大小限制
      maxFileSize: 1024MB
      maxRequestSize: 10240MB
  jackson: # Jackson配置
    timeZone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss
  datasource: # 数据库配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/faster?useUnicode=true&characterEncoding=UTF-8
    username: faster
    password: faster

# Security配置
security:
  ignored:
    - assets/**
    - vendor/**
    - favicon.ico
    - login.html
